version: '3.2'

# This file is in this sub-folder so that the group of containers has a useful name in Docker UIs

services:
  client:
    build: ../client
    container_name: "hfu-2021-client"
    restart: unless-stopped
    ports:
      - '8081:8081'
    volumes:
      - ../../:/var/www/html
    depends_on:
      - server

  server:
    build: ../server
    container_name: "hfu-2021-server"
    restart: unless-stopped
    volumes:
      - ../../:/usr/src/app
    ports:
      - '3000:3000'

  tests:
    build: ../tests
    container_name: "hfu-2021-tests"
    restart: unless-stopped
    volumes:
      - ../../src/data:/usr/src/app
    ports:
      - '3001:3001'
